// Automatically generated by scripts/gen_cache_key.py, do not modify.
//
// Hash and logical-equality over the FlatBuffers accessors, with the field
// policy taken from the 'cache_ignore' schema annotation. Reads the
// caller's buffer in place: no UnPack, no allocation, no reflection.

#pragma once

#include <cstdint>
#include <string_view>
#include <type_traits>

#include <hipdnn_flatbuffers_sdk/data_objects/graph_generated.h>

namespace hipdnn_flatbuffers_sdk::data_objects::cachekey
{

/// Streaming FNV-1a. Folds a value at a time so nothing is buffered.
class Hasher
{
public:
    /// Presence and union discriminators are folded through this, so an absent
    /// field and a field holding the tag's value cannot collide.
    void tag(uint8_t value)
    {
        _state ^= value;
        _state *= PRIME;
    }

    template <typename TValue>
    void raw(TValue value)
    {
        static_assert(std::is_trivially_copyable_v<TValue>);
        uint8_t bytes[sizeof(TValue)];
        __builtin_memcpy(bytes, &value, sizeof(TValue));
        for(uint8_t byte : bytes)
        {
            tag(byte);
        }
    }

    uint64_t value() const
    {
        return _state;
    }

private:
    static constexpr uint64_t OFFSET_BASIS = 1469598103934665603ULL;
    static constexpr uint64_t PRIME        = 1099511628211ULL;

    uint64_t _state = OFFSET_BASIS;
};

inline void hashAppend(Hasher& hasher, const BFloat16Value* value);
inline bool logicallyEqual(const BFloat16Value* a, const BFloat16Value* b);
inline void hashAppend(Hasher& hasher, const BatchnormAttributes* value);
inline bool logicallyEqual(const BatchnormAttributes* a, const BatchnormAttributes* b);
inline void hashAppend(Hasher& hasher, const BatchnormBackwardAttributes* value);
inline bool logicallyEqual(const BatchnormBackwardAttributes* a, const BatchnormBackwardAttributes* b);
inline void hashAppend(Hasher& hasher, const BatchnormInferenceAttributes* value);
inline bool logicallyEqual(const BatchnormInferenceAttributes* a, const BatchnormInferenceAttributes* b);
inline void hashAppend(Hasher& hasher, const BatchnormInferenceAttributesVarianceExt* value);
inline bool logicallyEqual(const BatchnormInferenceAttributesVarianceExt* a, const BatchnormInferenceAttributesVarianceExt* b);
inline void hashAppend(Hasher& hasher, const BlockScaleDequantizeAttributes* value);
inline bool logicallyEqual(const BlockScaleDequantizeAttributes* a, const BlockScaleDequantizeAttributes* b);
inline void hashAppend(Hasher& hasher, const BlockScaleQuantizeAttributes* value);
inline bool logicallyEqual(const BlockScaleQuantizeAttributes* a, const BlockScaleQuantizeAttributes* b);
inline void hashAppend(Hasher& hasher, const BoolValue* value);
inline bool logicallyEqual(const BoolValue* a, const BoolValue* b);
inline void hashAppend(Hasher& hasher, const ConvolutionBwdAttributes* value);
inline bool logicallyEqual(const ConvolutionBwdAttributes* a, const ConvolutionBwdAttributes* b);
inline void hashAppend(Hasher& hasher, const ConvolutionFwdAttributes* value);
inline bool logicallyEqual(const ConvolutionFwdAttributes* a, const ConvolutionFwdAttributes* b);
inline void hashAppend(Hasher& hasher, const ConvolutionWrwAttributes* value);
inline bool logicallyEqual(const ConvolutionWrwAttributes* a, const ConvolutionWrwAttributes* b);
inline void hashAppend(Hasher& hasher, const CustomOpAttributes* value);
inline bool logicallyEqual(const CustomOpAttributes* a, const CustomOpAttributes* b);
inline void hashAppend(Hasher& hasher, const Float16Value* value);
inline bool logicallyEqual(const Float16Value* a, const Float16Value* b);
inline void hashAppend(Hasher& hasher, const Float32Value* value);
inline bool logicallyEqual(const Float32Value* a, const Float32Value* b);
inline void hashAppend(Hasher& hasher, const Float64Value* value);
inline bool logicallyEqual(const Float64Value* a, const Float64Value* b);
inline void hashAppend(Hasher& hasher, const Float8Value* value);
inline bool logicallyEqual(const Float8Value* a, const Float8Value* b);
inline void hashAppend(Hasher& hasher, const Graph* value);
inline bool logicallyEqual(const Graph* a, const Graph* b);
inline void hashAppend(Hasher& hasher, const Int32Value* value);
inline bool logicallyEqual(const Int32Value* a, const Int32Value* b);
inline void hashAppend(Hasher& hasher, const Int64Value* value);
inline bool logicallyEqual(const Int64Value* a, const Int64Value* b);
inline void hashAppend(Hasher& hasher, const LayernormAttributes* value);
inline bool logicallyEqual(const LayernormAttributes* a, const LayernormAttributes* b);
inline void hashAppend(Hasher& hasher, const LayernormBackwardAttributes* value);
inline bool logicallyEqual(const LayernormBackwardAttributes* a, const LayernormBackwardAttributes* b);
inline void hashAppend(Hasher& hasher, const MatmulAttributes* value);
inline bool logicallyEqual(const MatmulAttributes* a, const MatmulAttributes* b);
inline void hashAppend(Hasher& hasher, const MoeGroupedMatmulAttributes* value);
inline bool logicallyEqual(const MoeGroupedMatmulAttributes* a, const MoeGroupedMatmulAttributes* b);
inline void hashAppend(Hasher& hasher, const MoeGroupedMatmulBwdAttributes* value);
inline bool logicallyEqual(const MoeGroupedMatmulBwdAttributes* a, const MoeGroupedMatmulBwdAttributes* b);
inline void hashAppend(Hasher& hasher, const Node* value);
inline bool logicallyEqual(const Node* a, const Node* b);
inline void hashAppend(Hasher& hasher, const PointwiseAttributes* value);
inline bool logicallyEqual(const PointwiseAttributes* a, const PointwiseAttributes* b);
inline void hashAppend(Hasher& hasher, const RMSNormAttributes* value);
inline bool logicallyEqual(const RMSNormAttributes* a, const RMSNormAttributes* b);
inline void hashAppend(Hasher& hasher, const RMSNormBackwardAttributes* value);
inline bool logicallyEqual(const RMSNormBackwardAttributes* a, const RMSNormBackwardAttributes* b);
inline void hashAppend(Hasher& hasher, const ReductionAttributes* value);
inline bool logicallyEqual(const ReductionAttributes* a, const ReductionAttributes* b);
inline void hashAppend(Hasher& hasher, const ResampleBwdAttributes* value);
inline bool logicallyEqual(const ResampleBwdAttributes* a, const ResampleBwdAttributes* b);
inline void hashAppend(Hasher& hasher, const ResampleFwdAttributes* value);
inline bool logicallyEqual(const ResampleFwdAttributes* a, const ResampleFwdAttributes* b);
inline void hashAppend(Hasher& hasher, const SdpaAttributes* value);
inline bool logicallyEqual(const SdpaAttributes* a, const SdpaAttributes* b);
inline void hashAppend(Hasher& hasher, const SdpaBackwardAttributes* value);
inline bool logicallyEqual(const SdpaBackwardAttributes* a, const SdpaBackwardAttributes* b);
inline void hashAppend(Hasher& hasher, const TensorAttributes* value);
inline bool logicallyEqual(const TensorAttributes* a, const TensorAttributes* b);
inline void hashAppend(Hasher& hasher, NodeAttributes type, const void* value);
inline bool logicallyEqual(NodeAttributes aType, const void* a, NodeAttributes bType, const void* b);
inline void hashAppend(Hasher& hasher, TensorValue type, const void* value);
inline bool logicallyEqual(TensorValue aType, const void* a, TensorValue bType, const void* b);

inline void hashAppend(Hasher& hasher, NodeAttributes type, const void* value)
{
    hasher.raw(static_cast<uint8_t>(type));
    switch(type)
    {
    case NodeAttributes::BatchnormInferenceAttributes:
        hashAppend(hasher, static_cast<const BatchnormInferenceAttributes*>(value));
        break;
    case NodeAttributes::PointwiseAttributes:
        hashAppend(hasher, static_cast<const PointwiseAttributes*>(value));
        break;
    case NodeAttributes::BatchnormBackwardAttributes:
        hashAppend(hasher, static_cast<const BatchnormBackwardAttributes*>(value));
        break;
    case NodeAttributes::BatchnormAttributes:
        hashAppend(hasher, static_cast<const BatchnormAttributes*>(value));
        break;
    case NodeAttributes::ConvolutionFwdAttributes:
        hashAppend(hasher, static_cast<const ConvolutionFwdAttributes*>(value));
        break;
    case NodeAttributes::ConvolutionBwdAttributes:
        hashAppend(hasher, static_cast<const ConvolutionBwdAttributes*>(value));
        break;
    case NodeAttributes::ConvolutionWrwAttributes:
        hashAppend(hasher, static_cast<const ConvolutionWrwAttributes*>(value));
        break;
    case NodeAttributes::BatchnormInferenceAttributesVarianceExt:
        hashAppend(hasher, static_cast<const BatchnormInferenceAttributesVarianceExt*>(value));
        break;
    case NodeAttributes::MatmulAttributes:
        hashAppend(hasher, static_cast<const MatmulAttributes*>(value));
        break;
    case NodeAttributes::RMSNormAttributes:
        hashAppend(hasher, static_cast<const RMSNormAttributes*>(value));
        break;
    case NodeAttributes::LayernormAttributes:
        hashAppend(hasher, static_cast<const LayernormAttributes*>(value));
        break;
    case NodeAttributes::SdpaAttributes:
        hashAppend(hasher, static_cast<const SdpaAttributes*>(value));
        break;
    case NodeAttributes::BlockScaleDequantizeAttributes:
        hashAppend(hasher, static_cast<const BlockScaleDequantizeAttributes*>(value));
        break;
    case NodeAttributes::BlockScaleQuantizeAttributes:
        hashAppend(hasher, static_cast<const BlockScaleQuantizeAttributes*>(value));
        break;
    case NodeAttributes::SdpaBackwardAttributes:
        hashAppend(hasher, static_cast<const SdpaBackwardAttributes*>(value));
        break;
    case NodeAttributes::CustomOpAttributes:
        hashAppend(hasher, static_cast<const CustomOpAttributes*>(value));
        break;
    case NodeAttributes::RMSNormBackwardAttributes:
        hashAppend(hasher, static_cast<const RMSNormBackwardAttributes*>(value));
        break;
    case NodeAttributes::ReductionAttributes:
        hashAppend(hasher, static_cast<const ReductionAttributes*>(value));
        break;
    case NodeAttributes::ResampleFwdAttributes:
        hashAppend(hasher, static_cast<const ResampleFwdAttributes*>(value));
        break;
    case NodeAttributes::LayernormBackwardAttributes:
        hashAppend(hasher, static_cast<const LayernormBackwardAttributes*>(value));
        break;
    case NodeAttributes::ResampleBwdAttributes:
        hashAppend(hasher, static_cast<const ResampleBwdAttributes*>(value));
        break;
    case NodeAttributes::MoeGroupedMatmulAttributes:
        hashAppend(hasher, static_cast<const MoeGroupedMatmulAttributes*>(value));
        break;
    case NodeAttributes::MoeGroupedMatmulBwdAttributes:
        hashAppend(hasher, static_cast<const MoeGroupedMatmulBwdAttributes*>(value));
        break;
    default:
        break;
    }
}

inline bool logicallyEqual(NodeAttributes aType, const void* a, NodeAttributes bType, const void* b)
{
    if(aType != bType)
    {
        return false;
    }
    switch(aType)
    {
    case NodeAttributes::BatchnormInferenceAttributes:
        return logicallyEqual(static_cast<const BatchnormInferenceAttributes*>(a), static_cast<const BatchnormInferenceAttributes*>(b));
    case NodeAttributes::PointwiseAttributes:
        return logicallyEqual(static_cast<const PointwiseAttributes*>(a), static_cast<const PointwiseAttributes*>(b));
    case NodeAttributes::BatchnormBackwardAttributes:
        return logicallyEqual(static_cast<const BatchnormBackwardAttributes*>(a), static_cast<const BatchnormBackwardAttributes*>(b));
    case NodeAttributes::BatchnormAttributes:
        return logicallyEqual(static_cast<const BatchnormAttributes*>(a), static_cast<const BatchnormAttributes*>(b));
    case NodeAttributes::ConvolutionFwdAttributes:
        return logicallyEqual(static_cast<const ConvolutionFwdAttributes*>(a), static_cast<const ConvolutionFwdAttributes*>(b));
    case NodeAttributes::ConvolutionBwdAttributes:
        return logicallyEqual(static_cast<const ConvolutionBwdAttributes*>(a), static_cast<const ConvolutionBwdAttributes*>(b));
    case NodeAttributes::ConvolutionWrwAttributes:
        return logicallyEqual(static_cast<const ConvolutionWrwAttributes*>(a), static_cast<const ConvolutionWrwAttributes*>(b));
    case NodeAttributes::BatchnormInferenceAttributesVarianceExt:
        return logicallyEqual(static_cast<const BatchnormInferenceAttributesVarianceExt*>(a), static_cast<const BatchnormInferenceAttributesVarianceExt*>(b));
    case NodeAttributes::MatmulAttributes:
        return logicallyEqual(static_cast<const MatmulAttributes*>(a), static_cast<const MatmulAttributes*>(b));
    case NodeAttributes::RMSNormAttributes:
        return logicallyEqual(static_cast<const RMSNormAttributes*>(a), static_cast<const RMSNormAttributes*>(b));
    case NodeAttributes::LayernormAttributes:
        return logicallyEqual(static_cast<const LayernormAttributes*>(a), static_cast<const LayernormAttributes*>(b));
    case NodeAttributes::SdpaAttributes:
        return logicallyEqual(static_cast<const SdpaAttributes*>(a), static_cast<const SdpaAttributes*>(b));
    case NodeAttributes::BlockScaleDequantizeAttributes:
        return logicallyEqual(static_cast<const BlockScaleDequantizeAttributes*>(a), static_cast<const BlockScaleDequantizeAttributes*>(b));
    case NodeAttributes::BlockScaleQuantizeAttributes:
        return logicallyEqual(static_cast<const BlockScaleQuantizeAttributes*>(a), static_cast<const BlockScaleQuantizeAttributes*>(b));
    case NodeAttributes::SdpaBackwardAttributes:
        return logicallyEqual(static_cast<const SdpaBackwardAttributes*>(a), static_cast<const SdpaBackwardAttributes*>(b));
    case NodeAttributes::CustomOpAttributes:
        return logicallyEqual(static_cast<const CustomOpAttributes*>(a), static_cast<const CustomOpAttributes*>(b));
    case NodeAttributes::RMSNormBackwardAttributes:
        return logicallyEqual(static_cast<const RMSNormBackwardAttributes*>(a), static_cast<const RMSNormBackwardAttributes*>(b));
    case NodeAttributes::ReductionAttributes:
        return logicallyEqual(static_cast<const ReductionAttributes*>(a), static_cast<const ReductionAttributes*>(b));
    case NodeAttributes::ResampleFwdAttributes:
        return logicallyEqual(static_cast<const ResampleFwdAttributes*>(a), static_cast<const ResampleFwdAttributes*>(b));
    case NodeAttributes::LayernormBackwardAttributes:
        return logicallyEqual(static_cast<const LayernormBackwardAttributes*>(a), static_cast<const LayernormBackwardAttributes*>(b));
    case NodeAttributes::ResampleBwdAttributes:
        return logicallyEqual(static_cast<const ResampleBwdAttributes*>(a), static_cast<const ResampleBwdAttributes*>(b));
    case NodeAttributes::MoeGroupedMatmulAttributes:
        return logicallyEqual(static_cast<const MoeGroupedMatmulAttributes*>(a), static_cast<const MoeGroupedMatmulAttributes*>(b));
    case NodeAttributes::MoeGroupedMatmulBwdAttributes:
        return logicallyEqual(static_cast<const MoeGroupedMatmulBwdAttributes*>(a), static_cast<const MoeGroupedMatmulBwdAttributes*>(b));
    default:
        return true;
    }
}

inline void hashAppend(Hasher& hasher, TensorValue type, const void* value)
{
    hasher.raw(static_cast<uint8_t>(type));
    switch(type)
    {
    case TensorValue::Float32Value:
        hashAppend(hasher, static_cast<const Float32Value*>(value));
        break;
    case TensorValue::Float16Value:
        hashAppend(hasher, static_cast<const Float16Value*>(value));
        break;
    case TensorValue::BFloat16Value:
        hashAppend(hasher, static_cast<const BFloat16Value*>(value));
        break;
    case TensorValue::Float8Value:
        hashAppend(hasher, static_cast<const Float8Value*>(value));
        break;
    case TensorValue::Int32Value:
        hashAppend(hasher, static_cast<const Int32Value*>(value));
        break;
    case TensorValue::Float64Value:
        hashAppend(hasher, static_cast<const Float64Value*>(value));
        break;
    case TensorValue::Int64Value:
        hashAppend(hasher, static_cast<const Int64Value*>(value));
        break;
    case TensorValue::BoolValue:
        hashAppend(hasher, static_cast<const BoolValue*>(value));
        break;
    default:
        break;
    }
}

inline bool logicallyEqual(TensorValue aType, const void* a, TensorValue bType, const void* b)
{
    if(aType != bType)
    {
        return false;
    }
    switch(aType)
    {
    case TensorValue::Float32Value:
        return logicallyEqual(static_cast<const Float32Value*>(a), static_cast<const Float32Value*>(b));
    case TensorValue::Float16Value:
        return logicallyEqual(static_cast<const Float16Value*>(a), static_cast<const Float16Value*>(b));
    case TensorValue::BFloat16Value:
        return logicallyEqual(static_cast<const BFloat16Value*>(a), static_cast<const BFloat16Value*>(b));
    case TensorValue::Float8Value:
        return logicallyEqual(static_cast<const Float8Value*>(a), static_cast<const Float8Value*>(b));
    case TensorValue::Int32Value:
        return logicallyEqual(static_cast<const Int32Value*>(a), static_cast<const Int32Value*>(b));
    case TensorValue::Float64Value:
        return logicallyEqual(static_cast<const Float64Value*>(a), static_cast<const Float64Value*>(b));
    case TensorValue::Int64Value:
        return logicallyEqual(static_cast<const Int64Value*>(a), static_cast<const Int64Value*>(b));
    case TensorValue::BoolValue:
        return logicallyEqual(static_cast<const BoolValue*>(a), static_cast<const BoolValue*>(b));
    default:
        return true;
    }
}

inline void hashAppend(Hasher& hasher, const BFloat16Value* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->value());
}

inline bool logicallyEqual(const BFloat16Value* a, const BFloat16Value* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->value() != b->value())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const BatchnormAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->x_tensor_uid());
    hasher.raw(value->scale_tensor_uid());
    hasher.raw(value->bias_tensor_uid());
    hasher.raw(value->epsilon_tensor_uid());
    {
        const auto* items = value->peer_stats_tensor_uid();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto optional = value->prev_running_mean_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->prev_running_variance_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->momentum_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(value->y_tensor_uid());
    {
        const auto optional = value->mean_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->inv_variance_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->next_running_mean_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->next_running_variance_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
}

inline bool logicallyEqual(const BatchnormAttributes* a, const BatchnormAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->scale_tensor_uid() != b->scale_tensor_uid())
    {
        return false;
    }
    if(a->bias_tensor_uid() != b->bias_tensor_uid())
    {
        return false;
    }
    if(a->epsilon_tensor_uid() != b->epsilon_tensor_uid())
    {
        return false;
    }
    {
        const auto* aItems = a->peer_stats_tensor_uid();
        const auto* bItems = b->peer_stats_tensor_uid();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    if(a->prev_running_mean_tensor_uid() != b->prev_running_mean_tensor_uid())
    {
        return false;
    }
    if(a->prev_running_variance_tensor_uid() != b->prev_running_variance_tensor_uid())
    {
        return false;
    }
    if(a->momentum_tensor_uid() != b->momentum_tensor_uid())
    {
        return false;
    }
    if(a->y_tensor_uid() != b->y_tensor_uid())
    {
        return false;
    }
    if(a->mean_tensor_uid() != b->mean_tensor_uid())
    {
        return false;
    }
    if(a->inv_variance_tensor_uid() != b->inv_variance_tensor_uid())
    {
        return false;
    }
    if(a->next_running_mean_tensor_uid() != b->next_running_mean_tensor_uid())
    {
        return false;
    }
    if(a->next_running_variance_tensor_uid() != b->next_running_variance_tensor_uid())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const BatchnormBackwardAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->dy_tensor_uid());
    hasher.raw(value->x_tensor_uid());
    {
        const auto optional = value->mean_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->inv_variance_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(value->scale_tensor_uid());
    {
        const auto* items = value->peer_stats_tensor_uid();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    hasher.raw(value->dx_tensor_uid());
    hasher.raw(value->dscale_tensor_uid());
    hasher.raw(value->dbias_tensor_uid());
}

inline bool logicallyEqual(const BatchnormBackwardAttributes* a, const BatchnormBackwardAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->dy_tensor_uid() != b->dy_tensor_uid())
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->mean_tensor_uid() != b->mean_tensor_uid())
    {
        return false;
    }
    if(a->inv_variance_tensor_uid() != b->inv_variance_tensor_uid())
    {
        return false;
    }
    if(a->scale_tensor_uid() != b->scale_tensor_uid())
    {
        return false;
    }
    {
        const auto* aItems = a->peer_stats_tensor_uid();
        const auto* bItems = b->peer_stats_tensor_uid();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    if(a->dx_tensor_uid() != b->dx_tensor_uid())
    {
        return false;
    }
    if(a->dscale_tensor_uid() != b->dscale_tensor_uid())
    {
        return false;
    }
    if(a->dbias_tensor_uid() != b->dbias_tensor_uid())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const BatchnormInferenceAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->x_tensor_uid());
    hasher.raw(value->mean_tensor_uid());
    hasher.raw(value->inv_variance_tensor_uid());
    hasher.raw(value->scale_tensor_uid());
    hasher.raw(value->bias_tensor_uid());
    hasher.raw(value->y_tensor_uid());
}

inline bool logicallyEqual(const BatchnormInferenceAttributes* a, const BatchnormInferenceAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->mean_tensor_uid() != b->mean_tensor_uid())
    {
        return false;
    }
    if(a->inv_variance_tensor_uid() != b->inv_variance_tensor_uid())
    {
        return false;
    }
    if(a->scale_tensor_uid() != b->scale_tensor_uid())
    {
        return false;
    }
    if(a->bias_tensor_uid() != b->bias_tensor_uid())
    {
        return false;
    }
    if(a->y_tensor_uid() != b->y_tensor_uid())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const BatchnormInferenceAttributesVarianceExt* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->x_tensor_uid());
    hasher.raw(value->mean_tensor_uid());
    hasher.raw(value->variance_tensor_uid());
    hasher.raw(value->scale_tensor_uid());
    hasher.raw(value->bias_tensor_uid());
    hasher.raw(value->y_tensor_uid());
    hasher.raw(value->epsilon_tensor_uid());
}

inline bool logicallyEqual(const BatchnormInferenceAttributesVarianceExt* a, const BatchnormInferenceAttributesVarianceExt* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->mean_tensor_uid() != b->mean_tensor_uid())
    {
        return false;
    }
    if(a->variance_tensor_uid() != b->variance_tensor_uid())
    {
        return false;
    }
    if(a->scale_tensor_uid() != b->scale_tensor_uid())
    {
        return false;
    }
    if(a->bias_tensor_uid() != b->bias_tensor_uid())
    {
        return false;
    }
    if(a->y_tensor_uid() != b->y_tensor_uid())
    {
        return false;
    }
    if(a->epsilon_tensor_uid() != b->epsilon_tensor_uid())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const BlockScaleDequantizeAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->x_tensor_uid());
    hasher.raw(value->scale_tensor_uid());
    hasher.raw(value->y_tensor_uid());
    {
        const auto* items = value->block_size();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    hasher.raw(value->is_negative_scale());
}

inline bool logicallyEqual(const BlockScaleDequantizeAttributes* a, const BlockScaleDequantizeAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->scale_tensor_uid() != b->scale_tensor_uid())
    {
        return false;
    }
    if(a->y_tensor_uid() != b->y_tensor_uid())
    {
        return false;
    }
    {
        const auto* aItems = a->block_size();
        const auto* bItems = b->block_size();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    if(a->is_negative_scale() != b->is_negative_scale())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const BlockScaleQuantizeAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->x_tensor_uid());
    hasher.raw(value->y_tensor_uid());
    hasher.raw(value->scale_tensor_uid());
    hasher.raw(value->block_size());
    {
        const auto optional = value->axis();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(value->transpose());
}

inline bool logicallyEqual(const BlockScaleQuantizeAttributes* a, const BlockScaleQuantizeAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->y_tensor_uid() != b->y_tensor_uid())
    {
        return false;
    }
    if(a->scale_tensor_uid() != b->scale_tensor_uid())
    {
        return false;
    }
    if(a->block_size() != b->block_size())
    {
        return false;
    }
    if(a->axis() != b->axis())
    {
        return false;
    }
    if(a->transpose() != b->transpose())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const BoolValue* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->value());
}

inline bool logicallyEqual(const BoolValue* a, const BoolValue* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->value() != b->value())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const ConvolutionBwdAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->dy_tensor_uid());
    hasher.raw(value->w_tensor_uid());
    hasher.raw(value->dx_tensor_uid());
    {
        const auto* items = value->pre_padding();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->post_padding();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->stride();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->dilation();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    hasher.raw(static_cast<int64_t>(value->conv_mode()));
}

inline bool logicallyEqual(const ConvolutionBwdAttributes* a, const ConvolutionBwdAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->dy_tensor_uid() != b->dy_tensor_uid())
    {
        return false;
    }
    if(a->w_tensor_uid() != b->w_tensor_uid())
    {
        return false;
    }
    if(a->dx_tensor_uid() != b->dx_tensor_uid())
    {
        return false;
    }
    {
        const auto* aItems = a->pre_padding();
        const auto* bItems = b->pre_padding();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->post_padding();
        const auto* bItems = b->post_padding();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->stride();
        const auto* bItems = b->stride();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->dilation();
        const auto* bItems = b->dilation();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    if(a->conv_mode() != b->conv_mode())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const ConvolutionFwdAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->x_tensor_uid());
    hasher.raw(value->w_tensor_uid());
    hasher.raw(value->y_tensor_uid());
    {
        const auto* items = value->pre_padding();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->post_padding();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->stride();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->dilation();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    hasher.raw(static_cast<int64_t>(value->conv_mode()));
}

inline bool logicallyEqual(const ConvolutionFwdAttributes* a, const ConvolutionFwdAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->w_tensor_uid() != b->w_tensor_uid())
    {
        return false;
    }
    if(a->y_tensor_uid() != b->y_tensor_uid())
    {
        return false;
    }
    {
        const auto* aItems = a->pre_padding();
        const auto* bItems = b->pre_padding();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->post_padding();
        const auto* bItems = b->post_padding();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->stride();
        const auto* bItems = b->stride();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->dilation();
        const auto* bItems = b->dilation();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    if(a->conv_mode() != b->conv_mode())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const ConvolutionWrwAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->x_tensor_uid());
    hasher.raw(value->dy_tensor_uid());
    hasher.raw(value->dw_tensor_uid());
    {
        const auto* items = value->pre_padding();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->post_padding();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->stride();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->dilation();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    hasher.raw(static_cast<int64_t>(value->conv_mode()));
}

inline bool logicallyEqual(const ConvolutionWrwAttributes* a, const ConvolutionWrwAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->dy_tensor_uid() != b->dy_tensor_uid())
    {
        return false;
    }
    if(a->dw_tensor_uid() != b->dw_tensor_uid())
    {
        return false;
    }
    {
        const auto* aItems = a->pre_padding();
        const auto* bItems = b->pre_padding();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->post_padding();
        const auto* bItems = b->post_padding();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->stride();
        const auto* bItems = b->stride();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->dilation();
        const auto* bItems = b->dilation();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    if(a->conv_mode() != b->conv_mode())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const CustomOpAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    {
        const auto* text = value->custom_op_id();
        hasher.raw(static_cast<uint32_t>(text == nullptr ? 0 : text->size()));
        if(text != nullptr)
        {
            for(char character : *text)
            {
                hasher.tag(static_cast<uint8_t>(character));
            }
        }
    }
    {
        const auto* items = value->input_tensor_uids();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->output_tensor_uids();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->data();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
}

inline bool logicallyEqual(const CustomOpAttributes* a, const CustomOpAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    {
        const auto* aText = a->custom_op_id();
        const auto* bText = b->custom_op_id();
        if((aText == nullptr) != (bText == nullptr))
        {
            return false;
        }
        if(aText != nullptr && aText->string_view() != bText->string_view())
        {
            return false;
        }
    }
    {
        const auto* aItems = a->input_tensor_uids();
        const auto* bItems = b->input_tensor_uids();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->output_tensor_uids();
        const auto* bItems = b->output_tensor_uids();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->data();
        const auto* bItems = b->data();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const Float16Value* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->value());
}

inline bool logicallyEqual(const Float16Value* a, const Float16Value* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->value() != b->value())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const Float32Value* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->value());
}

inline bool logicallyEqual(const Float32Value* a, const Float32Value* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->value() != b->value())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const Float64Value* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->value());
}

inline bool logicallyEqual(const Float64Value* a, const Float64Value* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->value() != b->value())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const Float8Value* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->value());
}

inline bool logicallyEqual(const Float8Value* a, const Float8Value* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->value() != b->value())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const Graph* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(static_cast<int64_t>(value->compute_data_type()));
    hasher.raw(static_cast<int64_t>(value->intermediate_data_type()));
    hasher.raw(static_cast<int64_t>(value->io_data_type()));
    {
        const auto* items = value->tensors();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hashAppend(hasher, items->Get(index));
        }
    }
    {
        const auto* items = value->nodes();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hashAppend(hasher, items->Get(index));
        }
    }
}

inline bool logicallyEqual(const Graph* a, const Graph* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->compute_data_type() != b->compute_data_type())
    {
        return false;
    }
    if(a->intermediate_data_type() != b->intermediate_data_type())
    {
        return false;
    }
    if(a->io_data_type() != b->io_data_type())
    {
        return false;
    }
    {
        const auto* aItems = a->tensors();
        const auto* bItems = b->tensors();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(!logicallyEqual(aItems->Get(index), bItems->Get(index)))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->nodes();
        const auto* bItems = b->nodes();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(!logicallyEqual(aItems->Get(index), bItems->Get(index)))
            {
                return false;
            }
        }
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const Int32Value* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->value());
}

inline bool logicallyEqual(const Int32Value* a, const Int32Value* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->value() != b->value())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const Int64Value* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->value());
}

inline bool logicallyEqual(const Int64Value* a, const Int64Value* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->value() != b->value())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const LayernormAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->x_tensor_uid());
    hasher.raw(value->scale_tensor_uid());
    hasher.raw(value->bias_tensor_uid());
    hasher.raw(value->epsilon_tensor_uid());
    hasher.raw(value->y_tensor_uid());
    hasher.raw(value->normalized_dim_count());
    {
        const auto optional = value->mean_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->inv_variance_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(static_cast<int64_t>(value->forward_phase()));
}

inline bool logicallyEqual(const LayernormAttributes* a, const LayernormAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->scale_tensor_uid() != b->scale_tensor_uid())
    {
        return false;
    }
    if(a->bias_tensor_uid() != b->bias_tensor_uid())
    {
        return false;
    }
    if(a->epsilon_tensor_uid() != b->epsilon_tensor_uid())
    {
        return false;
    }
    if(a->y_tensor_uid() != b->y_tensor_uid())
    {
        return false;
    }
    if(a->normalized_dim_count() != b->normalized_dim_count())
    {
        return false;
    }
    if(a->mean_tensor_uid() != b->mean_tensor_uid())
    {
        return false;
    }
    if(a->inv_variance_tensor_uid() != b->inv_variance_tensor_uid())
    {
        return false;
    }
    if(a->forward_phase() != b->forward_phase())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const LayernormBackwardAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->dy_tensor_uid());
    hasher.raw(value->x_tensor_uid());
    hasher.raw(value->scale_tensor_uid());
    {
        const auto optional = value->mean_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->inv_variance_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->epsilon_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(value->dx_tensor_uid());
    hasher.raw(value->dscale_tensor_uid());
    hasher.raw(value->dbias_tensor_uid());
    hasher.raw(value->normalized_dim_count());
}

inline bool logicallyEqual(const LayernormBackwardAttributes* a, const LayernormBackwardAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->dy_tensor_uid() != b->dy_tensor_uid())
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->scale_tensor_uid() != b->scale_tensor_uid())
    {
        return false;
    }
    if(a->mean_tensor_uid() != b->mean_tensor_uid())
    {
        return false;
    }
    if(a->inv_variance_tensor_uid() != b->inv_variance_tensor_uid())
    {
        return false;
    }
    if(a->epsilon_tensor_uid() != b->epsilon_tensor_uid())
    {
        return false;
    }
    if(a->dx_tensor_uid() != b->dx_tensor_uid())
    {
        return false;
    }
    if(a->dscale_tensor_uid() != b->dscale_tensor_uid())
    {
        return false;
    }
    if(a->dbias_tensor_uid() != b->dbias_tensor_uid())
    {
        return false;
    }
    if(a->normalized_dim_count() != b->normalized_dim_count())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const MatmulAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->a_tensor_uid());
    hasher.raw(value->b_tensor_uid());
    hasher.raw(value->c_tensor_uid());
}

inline bool logicallyEqual(const MatmulAttributes* a, const MatmulAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->a_tensor_uid() != b->a_tensor_uid())
    {
        return false;
    }
    if(a->b_tensor_uid() != b->b_tensor_uid())
    {
        return false;
    }
    if(a->c_tensor_uid() != b->c_tensor_uid())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const MoeGroupedMatmulAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->token_tensor_uid());
    hasher.raw(value->weight_tensor_uid());
    hasher.raw(value->first_token_offset_tensor_uid());
    {
        const auto optional = value->token_index_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->token_ks_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(value->output_tensor_uid());
    hasher.raw(static_cast<int64_t>(value->mode()));
    hasher.raw(value->top_k());
}

inline bool logicallyEqual(const MoeGroupedMatmulAttributes* a, const MoeGroupedMatmulAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->token_tensor_uid() != b->token_tensor_uid())
    {
        return false;
    }
    if(a->weight_tensor_uid() != b->weight_tensor_uid())
    {
        return false;
    }
    if(a->first_token_offset_tensor_uid() != b->first_token_offset_tensor_uid())
    {
        return false;
    }
    if(a->token_index_tensor_uid() != b->token_index_tensor_uid())
    {
        return false;
    }
    if(a->token_ks_tensor_uid() != b->token_ks_tensor_uid())
    {
        return false;
    }
    if(a->output_tensor_uid() != b->output_tensor_uid())
    {
        return false;
    }
    if(a->mode() != b->mode())
    {
        return false;
    }
    if(a->top_k() != b->top_k())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const MoeGroupedMatmulBwdAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->doutput_tensor_uid());
    hasher.raw(value->token_tensor_uid());
    hasher.raw(value->first_token_offset_tensor_uid());
    hasher.raw(value->dweight_tensor_uid());
}

inline bool logicallyEqual(const MoeGroupedMatmulBwdAttributes* a, const MoeGroupedMatmulBwdAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->doutput_tensor_uid() != b->doutput_tensor_uid())
    {
        return false;
    }
    if(a->token_tensor_uid() != b->token_tensor_uid())
    {
        return false;
    }
    if(a->first_token_offset_tensor_uid() != b->first_token_offset_tensor_uid())
    {
        return false;
    }
    if(a->dweight_tensor_uid() != b->dweight_tensor_uid())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const Node* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(static_cast<int64_t>(value->compute_data_type()));
    hashAppend(hasher, value->attributes_type(), value->attributes());
}

inline bool logicallyEqual(const Node* a, const Node* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->compute_data_type() != b->compute_data_type())
    {
        return false;
    }
    if(!logicallyEqual(a->attributes_type(), a->attributes(), b->attributes_type(), b->attributes()))
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const PointwiseAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(static_cast<int64_t>(value->operation()));
    {
        const auto optional = value->relu_lower_clip();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->relu_upper_clip();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->relu_lower_clip_slope();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->axis_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(value->in_0_tensor_uid());
    {
        const auto optional = value->in_1_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->in_2_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(value->out_0_tensor_uid());
    {
        const auto optional = value->swish_beta();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->elu_alpha();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->softplus_beta();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
}

inline bool logicallyEqual(const PointwiseAttributes* a, const PointwiseAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->operation() != b->operation())
    {
        return false;
    }
    if(a->relu_lower_clip() != b->relu_lower_clip())
    {
        return false;
    }
    if(a->relu_upper_clip() != b->relu_upper_clip())
    {
        return false;
    }
    if(a->relu_lower_clip_slope() != b->relu_lower_clip_slope())
    {
        return false;
    }
    if(a->axis_tensor_uid() != b->axis_tensor_uid())
    {
        return false;
    }
    if(a->in_0_tensor_uid() != b->in_0_tensor_uid())
    {
        return false;
    }
    if(a->in_1_tensor_uid() != b->in_1_tensor_uid())
    {
        return false;
    }
    if(a->in_2_tensor_uid() != b->in_2_tensor_uid())
    {
        return false;
    }
    if(a->out_0_tensor_uid() != b->out_0_tensor_uid())
    {
        return false;
    }
    if(a->swish_beta() != b->swish_beta())
    {
        return false;
    }
    if(a->elu_alpha() != b->elu_alpha())
    {
        return false;
    }
    if(a->softplus_beta() != b->softplus_beta())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const RMSNormAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->x_tensor_uid());
    hasher.raw(value->scale_tensor_uid());
    hasher.raw(value->epsilon_tensor_uid());
    hasher.raw(value->y_tensor_uid());
    {
        const auto optional = value->bias_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->inv_rms_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(static_cast<int64_t>(value->forward_phase()));
}

inline bool logicallyEqual(const RMSNormAttributes* a, const RMSNormAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->scale_tensor_uid() != b->scale_tensor_uid())
    {
        return false;
    }
    if(a->epsilon_tensor_uid() != b->epsilon_tensor_uid())
    {
        return false;
    }
    if(a->y_tensor_uid() != b->y_tensor_uid())
    {
        return false;
    }
    if(a->bias_tensor_uid() != b->bias_tensor_uid())
    {
        return false;
    }
    if(a->inv_rms_tensor_uid() != b->inv_rms_tensor_uid())
    {
        return false;
    }
    if(a->forward_phase() != b->forward_phase())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const RMSNormBackwardAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->dy_tensor_uid());
    hasher.raw(value->x_tensor_uid());
    hasher.raw(value->scale_tensor_uid());
    hasher.raw(value->inv_rms_tensor_uid());
    hasher.raw(value->dx_tensor_uid());
    hasher.raw(value->dscale_tensor_uid());
    {
        const auto optional = value->dbias_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
}

inline bool logicallyEqual(const RMSNormBackwardAttributes* a, const RMSNormBackwardAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->dy_tensor_uid() != b->dy_tensor_uid())
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->scale_tensor_uid() != b->scale_tensor_uid())
    {
        return false;
    }
    if(a->inv_rms_tensor_uid() != b->inv_rms_tensor_uid())
    {
        return false;
    }
    if(a->dx_tensor_uid() != b->dx_tensor_uid())
    {
        return false;
    }
    if(a->dscale_tensor_uid() != b->dscale_tensor_uid())
    {
        return false;
    }
    if(a->dbias_tensor_uid() != b->dbias_tensor_uid())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const ReductionAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(static_cast<int64_t>(value->mode()));
    hasher.raw(value->in_tensor_uid());
    hasher.raw(value->out_tensor_uid());
    hasher.raw(value->is_deterministic());
}

inline bool logicallyEqual(const ReductionAttributes* a, const ReductionAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->mode() != b->mode())
    {
        return false;
    }
    if(a->in_tensor_uid() != b->in_tensor_uid())
    {
        return false;
    }
    if(a->out_tensor_uid() != b->out_tensor_uid())
    {
        return false;
    }
    if(a->is_deterministic() != b->is_deterministic())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const ResampleBwdAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->dy_tensor_uid());
    hasher.raw(value->dx_tensor_uid());
    {
        const auto optional = value->index_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto* items = value->pre_padding();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->post_padding();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->stride();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->window();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    hasher.raw(static_cast<int64_t>(value->resample_mode()));
    hasher.raw(static_cast<int64_t>(value->padding_mode()));
}

inline bool logicallyEqual(const ResampleBwdAttributes* a, const ResampleBwdAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->dy_tensor_uid() != b->dy_tensor_uid())
    {
        return false;
    }
    if(a->dx_tensor_uid() != b->dx_tensor_uid())
    {
        return false;
    }
    if(a->index_tensor_uid() != b->index_tensor_uid())
    {
        return false;
    }
    {
        const auto* aItems = a->pre_padding();
        const auto* bItems = b->pre_padding();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->post_padding();
        const auto* bItems = b->post_padding();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->stride();
        const auto* bItems = b->stride();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->window();
        const auto* bItems = b->window();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    if(a->resample_mode() != b->resample_mode())
    {
        return false;
    }
    if(a->padding_mode() != b->padding_mode())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const ResampleFwdAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->x_tensor_uid());
    hasher.raw(value->y_tensor_uid());
    {
        const auto optional = value->index_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto* items = value->pre_padding();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->post_padding();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->stride();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->window();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    hasher.raw(static_cast<int64_t>(value->resample_mode()));
    hasher.raw(static_cast<int64_t>(value->padding_mode()));
    {
        const auto optional = value->generate_index();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
}

inline bool logicallyEqual(const ResampleFwdAttributes* a, const ResampleFwdAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->x_tensor_uid() != b->x_tensor_uid())
    {
        return false;
    }
    if(a->y_tensor_uid() != b->y_tensor_uid())
    {
        return false;
    }
    if(a->index_tensor_uid() != b->index_tensor_uid())
    {
        return false;
    }
    {
        const auto* aItems = a->pre_padding();
        const auto* bItems = b->pre_padding();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->post_padding();
        const auto* bItems = b->post_padding();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->stride();
        const auto* bItems = b->stride();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->window();
        const auto* bItems = b->window();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    if(a->resample_mode() != b->resample_mode())
    {
        return false;
    }
    if(a->padding_mode() != b->padding_mode())
    {
        return false;
    }
    if(a->generate_index() != b->generate_index())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const SdpaAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->q_tensor_uid());
    hasher.raw(value->k_tensor_uid());
    hasher.raw(value->v_tensor_uid());
    hasher.raw(value->o_tensor_uid());
    {
        const auto optional = value->attn_mask_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->scale_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->seq_len_q_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->seq_len_kv_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->seed_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->offset_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->dropout_mask_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->dropout_scale_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->page_table_k_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->page_table_v_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->block_mask_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->sink_token_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->descale_q_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->descale_k_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->descale_v_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->descale_s_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->scale_s_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->scale_o_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->stats_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->max_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->sum_exp_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->rng_dump_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->amax_s_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->amax_o_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->generate_stats();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(value->alibi_mask());
    hasher.raw(value->padding_mask());
    hasher.raw(value->causal_mask());
    hasher.raw(value->causal_mask_bottom_right());
    {
        const auto optional = value->dropout_probability();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->attn_scale_value();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->left_bound();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->right_bound();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->max_seq_len_kv();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(static_cast<int64_t>(value->diagonal_alignment()));
    hasher.raw(static_cast<int64_t>(value->mma_core_mode()));
    hasher.raw(static_cast<int64_t>(value->implementation()));
}

inline bool logicallyEqual(const SdpaAttributes* a, const SdpaAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->q_tensor_uid() != b->q_tensor_uid())
    {
        return false;
    }
    if(a->k_tensor_uid() != b->k_tensor_uid())
    {
        return false;
    }
    if(a->v_tensor_uid() != b->v_tensor_uid())
    {
        return false;
    }
    if(a->o_tensor_uid() != b->o_tensor_uid())
    {
        return false;
    }
    if(a->attn_mask_tensor_uid() != b->attn_mask_tensor_uid())
    {
        return false;
    }
    if(a->scale_tensor_uid() != b->scale_tensor_uid())
    {
        return false;
    }
    if(a->seq_len_q_tensor_uid() != b->seq_len_q_tensor_uid())
    {
        return false;
    }
    if(a->seq_len_kv_tensor_uid() != b->seq_len_kv_tensor_uid())
    {
        return false;
    }
    if(a->seed_tensor_uid() != b->seed_tensor_uid())
    {
        return false;
    }
    if(a->offset_tensor_uid() != b->offset_tensor_uid())
    {
        return false;
    }
    if(a->dropout_mask_tensor_uid() != b->dropout_mask_tensor_uid())
    {
        return false;
    }
    if(a->dropout_scale_tensor_uid() != b->dropout_scale_tensor_uid())
    {
        return false;
    }
    if(a->page_table_k_tensor_uid() != b->page_table_k_tensor_uid())
    {
        return false;
    }
    if(a->page_table_v_tensor_uid() != b->page_table_v_tensor_uid())
    {
        return false;
    }
    if(a->block_mask_tensor_uid() != b->block_mask_tensor_uid())
    {
        return false;
    }
    if(a->sink_token_tensor_uid() != b->sink_token_tensor_uid())
    {
        return false;
    }
    if(a->descale_q_tensor_uid() != b->descale_q_tensor_uid())
    {
        return false;
    }
    if(a->descale_k_tensor_uid() != b->descale_k_tensor_uid())
    {
        return false;
    }
    if(a->descale_v_tensor_uid() != b->descale_v_tensor_uid())
    {
        return false;
    }
    if(a->descale_s_tensor_uid() != b->descale_s_tensor_uid())
    {
        return false;
    }
    if(a->scale_s_tensor_uid() != b->scale_s_tensor_uid())
    {
        return false;
    }
    if(a->scale_o_tensor_uid() != b->scale_o_tensor_uid())
    {
        return false;
    }
    if(a->stats_tensor_uid() != b->stats_tensor_uid())
    {
        return false;
    }
    if(a->max_tensor_uid() != b->max_tensor_uid())
    {
        return false;
    }
    if(a->sum_exp_tensor_uid() != b->sum_exp_tensor_uid())
    {
        return false;
    }
    if(a->rng_dump_tensor_uid() != b->rng_dump_tensor_uid())
    {
        return false;
    }
    if(a->amax_s_tensor_uid() != b->amax_s_tensor_uid())
    {
        return false;
    }
    if(a->amax_o_tensor_uid() != b->amax_o_tensor_uid())
    {
        return false;
    }
    if(a->generate_stats() != b->generate_stats())
    {
        return false;
    }
    if(a->alibi_mask() != b->alibi_mask())
    {
        return false;
    }
    if(a->padding_mask() != b->padding_mask())
    {
        return false;
    }
    if(a->causal_mask() != b->causal_mask())
    {
        return false;
    }
    if(a->causal_mask_bottom_right() != b->causal_mask_bottom_right())
    {
        return false;
    }
    if(a->dropout_probability() != b->dropout_probability())
    {
        return false;
    }
    if(a->attn_scale_value() != b->attn_scale_value())
    {
        return false;
    }
    if(a->left_bound() != b->left_bound())
    {
        return false;
    }
    if(a->right_bound() != b->right_bound())
    {
        return false;
    }
    if(a->max_seq_len_kv() != b->max_seq_len_kv())
    {
        return false;
    }
    if(a->diagonal_alignment() != b->diagonal_alignment())
    {
        return false;
    }
    if(a->mma_core_mode() != b->mma_core_mode())
    {
        return false;
    }
    if(a->implementation() != b->implementation())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const SdpaBackwardAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->q_tensor_uid());
    hasher.raw(value->k_tensor_uid());
    hasher.raw(value->v_tensor_uid());
    hasher.raw(value->o_tensor_uid());
    hasher.raw(value->do_tensor_uid());
    hasher.raw(value->stats_tensor_uid());
    hasher.raw(value->dq_tensor_uid());
    hasher.raw(value->dk_tensor_uid());
    hasher.raw(value->dv_tensor_uid());
    {
        const auto optional = value->scale_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->attn_mask_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->seq_len_q_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->seq_len_kv_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->seed_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->offset_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->dropout_mask_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->dropout_scale_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->dropout_scale_inv_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->dbias_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(value->alibi_mask());
    hasher.raw(value->padding_mask());
    hasher.raw(value->causal_mask());
    hasher.raw(value->causal_mask_bottom_right());
    {
        const auto optional = value->dropout_probability();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->attn_scale_value();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->left_bound();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    {
        const auto optional = value->right_bound();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(static_cast<int64_t>(value->diagonal_alignment()));
}

inline bool logicallyEqual(const SdpaBackwardAttributes* a, const SdpaBackwardAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->q_tensor_uid() != b->q_tensor_uid())
    {
        return false;
    }
    if(a->k_tensor_uid() != b->k_tensor_uid())
    {
        return false;
    }
    if(a->v_tensor_uid() != b->v_tensor_uid())
    {
        return false;
    }
    if(a->o_tensor_uid() != b->o_tensor_uid())
    {
        return false;
    }
    if(a->do_tensor_uid() != b->do_tensor_uid())
    {
        return false;
    }
    if(a->stats_tensor_uid() != b->stats_tensor_uid())
    {
        return false;
    }
    if(a->dq_tensor_uid() != b->dq_tensor_uid())
    {
        return false;
    }
    if(a->dk_tensor_uid() != b->dk_tensor_uid())
    {
        return false;
    }
    if(a->dv_tensor_uid() != b->dv_tensor_uid())
    {
        return false;
    }
    if(a->scale_tensor_uid() != b->scale_tensor_uid())
    {
        return false;
    }
    if(a->attn_mask_tensor_uid() != b->attn_mask_tensor_uid())
    {
        return false;
    }
    if(a->seq_len_q_tensor_uid() != b->seq_len_q_tensor_uid())
    {
        return false;
    }
    if(a->seq_len_kv_tensor_uid() != b->seq_len_kv_tensor_uid())
    {
        return false;
    }
    if(a->seed_tensor_uid() != b->seed_tensor_uid())
    {
        return false;
    }
    if(a->offset_tensor_uid() != b->offset_tensor_uid())
    {
        return false;
    }
    if(a->dropout_mask_tensor_uid() != b->dropout_mask_tensor_uid())
    {
        return false;
    }
    if(a->dropout_scale_tensor_uid() != b->dropout_scale_tensor_uid())
    {
        return false;
    }
    if(a->dropout_scale_inv_tensor_uid() != b->dropout_scale_inv_tensor_uid())
    {
        return false;
    }
    if(a->dbias_tensor_uid() != b->dbias_tensor_uid())
    {
        return false;
    }
    if(a->alibi_mask() != b->alibi_mask())
    {
        return false;
    }
    if(a->padding_mask() != b->padding_mask())
    {
        return false;
    }
    if(a->causal_mask() != b->causal_mask())
    {
        return false;
    }
    if(a->causal_mask_bottom_right() != b->causal_mask_bottom_right())
    {
        return false;
    }
    if(a->dropout_probability() != b->dropout_probability())
    {
        return false;
    }
    if(a->attn_scale_value() != b->attn_scale_value())
    {
        return false;
    }
    if(a->left_bound() != b->left_bound())
    {
        return false;
    }
    if(a->right_bound() != b->right_bound())
    {
        return false;
    }
    if(a->diagonal_alignment() != b->diagonal_alignment())
    {
        return false;
    }
    return true;
}

inline void hashAppend(Hasher& hasher, const TensorAttributes* value)
{
    if(value == nullptr)
    {
        hasher.tag(0);
        return;
    }
    hasher.tag(1);
    hasher.raw(value->uid());
    hasher.raw(static_cast<int64_t>(value->data_type()));
    {
        const auto* items = value->strides();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    {
        const auto* items = value->dims();
        const uint32_t count = items == nullptr ? 0u : items->size();
        // Length first: {1, 2} and {1, 2, 0} must not fold alike.
        hasher.raw(count);
        for(uint32_t index = 0; index < count; ++index)
        {
            hasher.raw(items->Get(index));
        }
    }
    hasher.raw(value->virtual_());
    hashAppend(hasher, value->value_type(), value->value());
    hasher.raw(value->is_runtime_pass_by_value());
    {
        const auto optional = value->ragged_offset_tensor_uid();
        hasher.tag(optional ? 1 : 0);
        if(optional)
        {
            hasher.raw(*optional);
        }
    }
    hasher.raw(value->alignment());
}

inline bool logicallyEqual(const TensorAttributes* a, const TensorAttributes* b)
{
    if(a == b)
    {
        return true;
    }
    if(a == nullptr || b == nullptr)
    {
        return false;
    }
    if(a->uid() != b->uid())
    {
        return false;
    }
    if(a->data_type() != b->data_type())
    {
        return false;
    }
    {
        const auto* aItems = a->strides();
        const auto* bItems = b->strides();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    {
        const auto* aItems = a->dims();
        const auto* bItems = b->dims();
        const uint32_t aCount = aItems == nullptr ? 0u : aItems->size();
        const uint32_t bCount = bItems == nullptr ? 0u : bItems->size();
        if(aCount != bCount)
        {
            return false;
        }
        for(uint32_t index = 0; index < aCount; ++index)
        {
            if(aItems->Get(index) != bItems->Get(index))
            {
                return false;
            }
        }
    }
    if(a->virtual_() != b->virtual_())
    {
        return false;
    }
    if(!logicallyEqual(a->value_type(), a->value(), b->value_type(), b->value()))
    {
        return false;
    }
    if(a->is_runtime_pass_by_value() != b->is_runtime_pass_by_value())
    {
        return false;
    }
    if(a->ragged_offset_tensor_uid() != b->ragged_offset_tensor_uid())
    {
        return false;
    }
    if(a->alignment() != b->alignment())
    {
        return false;
    }
    return true;
}

} // namespace hipdnn_flatbuffers_sdk::data_objects::cachekey
